export interface ReceiptData {
  studentName: string
  phone: string
  feeAmount: number
  month: string
  paidAt: string
  ownerEmail: string
}

function formatMonth(month: string): string {
  const [year, mon] = month.split('-')
  return new Date(Number(year), Number(mon) - 1, 1).toLocaleDateString('en-GB', {
    month: 'long',
    year: 'numeric',
  })
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

export async function generateReceipt(data: ReceiptData): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()

  const marginL = 20
  const marginR = 190
  const col2 = 80

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.text('PayRemind', 105, 28, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(13)
  doc.text('Fee Payment Receipt', 105, 37, { align: 'center' })

  // Separator
  doc.setLineWidth(0.5)
  doc.line(marginL, 43, marginR, 43)

  // Fields
  const fields: [string, string][] = [
    ['Student Name', data.studentName],
    ['Month', formatMonth(data.month)],
    ['Amount Paid', `Rs. ${data.feeAmount.toLocaleString('en-IN')}`],
    ['Payment Date', formatDate(data.paidAt)],
    ['Processed by', data.ownerEmail],
  ]

  let y = 58
  for (const [label, value] of fields) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(label, marginL, y)

    doc.setFont('helvetica', 'normal')
    doc.text(value, col2, y)

    y += 13
  }

  // Section separator
  doc.setLineWidth(0.3)
  doc.line(marginL, y + 2, marginR, y + 2)

  // Footer
  doc.setLineWidth(0.3)
  doc.line(marginL, 283, marginR, 283)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(130)
  doc.text('Generated by PayRemind  •  payremind.in', 105, 290, { align: 'center' })
  doc.setTextColor(0)

  const filename = `Receipt_${data.studentName.replace(/\s+/g, '_')}_${data.month}.pdf`
  doc.save(filename)
}
