'use client'

import { useState } from 'react'
import { ChevronDown, ChevronUp } from 'lucide-react'
import type { Student, Payment, StudentWithPayment } from '@/types'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

interface Props {
  students: Student[]
  payments: Payment[]
  month: string
}

function formatMonth(month: string): string {
  const [year, mon] = month.split('-')
  return new Date(Number(year), Number(mon) - 1, 1).toLocaleDateString('en-GB', {
    month: 'long',
    year: 'numeric',
  })
}

function daysOverdue(month: string, dueDay: number): number {
  const due = new Date(`${month}-${String(dueDay).padStart(2, '0')}`)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  return Math.max(0, Math.floor((today.getTime() - due.getTime()) / 86400000))
}

export default function CollectionReport({ students, payments, month }: Props) {
  const [isOpen, setIsOpen] = useState(false)

  const swp: StudentWithPayment[] = students.map((s) => ({
    ...s,
    payment: payments.find((p) => p.student_id === s.id),
  }))

  const total = swp.length
  const paid = swp.filter((s) => s.payment?.status === 'paid')
  const unpaid = swp.filter((s) => s.payment?.status !== 'paid')
  const rate = total > 0 ? Math.round((paid.length / total) * 100) : 0
  const totalCollected = paid.reduce((sum, s) => sum + s.fee_amount, 0)
  const totalPending = unpaid.reduce((sum, s) => sum + s.fee_amount, 0)
  const defaulters = [...unpaid].sort((a, b) => b.fee_amount - a.fee_amount)

  async function handleDownload() {
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF()
    const marginL = 20
    const marginR = 190
    const col2 = 100

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(20)
    doc.text('PayRemind — Collection Report', 105, 26, { align: 'center' })

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(13)
    doc.text(formatMonth(month), 105, 35, { align: 'center' })

    doc.setLineWidth(0.5)
    doc.line(marginL, 41, marginR, 41)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Summary', marginL, 52)

    const stats: [string, string][] = [
      ['Total Students', String(total)],
      ['Paid', String(paid.length)],
      ['Unpaid / Overdue', String(unpaid.length)],
      ['Collection Rate', `${rate}%`],
      ['Total Collected', `Rs. ${totalCollected.toLocaleString('en-IN')}`],
      ['Total Pending', `Rs. ${totalPending.toLocaleString('en-IN')}`],
    ]

    let y = 63
    doc.setFontSize(11)
    for (const [label, value] of stats) {
      doc.setFont('helvetica', 'bold')
      doc.text(label, marginL, y)
      doc.setFont('helvetica', 'normal')
      doc.text(value, col2, y)
      y += 10
    }

    if (defaulters.length > 0) {
      y += 6
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.text('Top Defaulters', marginL, y)
      y += 10

      doc.setFontSize(10)
      doc.text('Name', marginL, y)
      doc.text('Fee (Rs.)', 110, y)
      doc.text('Days Overdue', 158, y)
      y += 2
      doc.setLineWidth(0.3)
      doc.line(marginL, y, marginR, y)
      y += 7

      doc.setFont('helvetica', 'normal')
      for (const s of defaulters) {
        const days = daysOverdue(month, s.due_day)
        doc.text(s.name, marginL, y)
        doc.text(String(s.fee_amount.toLocaleString('en-IN')), 110, y)
        doc.text(days > 0 ? `${days} day${days > 1 ? 's' : ''}` : 'Due today', 158, y)
        y += 9
        if (y > 270) break
      }
    }

    doc.setLineWidth(0.3)
    doc.line(marginL, 283, marginR, 283)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(130)
    doc.text('Generated by PayRemind  •  payremind.in', 105, 290, { align: 'center' })
    doc.setTextColor(0)

    doc.save(`CollectionReport_${month}.pdf`)
  }

  const formattedMonth = formatMonth(month)

  return (
    <Card>
      <CardContent className="p-0">
        <button
          onClick={() => setIsOpen((o) => !o)}
          className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-muted/40 transition-colors rounded-lg"
        >
          <span className="font-medium text-sm">📊 Collection Report — {formattedMonth}</span>
          {isOpen ? <ChevronUp className="size-4 text-muted-foreground" /> : <ChevronDown className="size-4 text-muted-foreground" />}
        </button>

        {isOpen && (
          <div className="px-4 pb-4 flex flex-col gap-4 border-t border-border pt-4">
            {/* Stats grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              <StatCell label="Total Students" value={String(total)} />
              <StatCell label="Paid" value={String(paid.length)} valueClass="text-green-600" />
              <StatCell label="Unpaid / Overdue" value={String(unpaid.length)} valueClass="text-red-600" />
              <StatCell label="Collection Rate" value={`${rate}%`} />
              <StatCell label="Total Collected" value={`₹${totalCollected.toLocaleString('en-IN')}`} valueClass="text-green-600" />
              <StatCell label="Total Pending" value={`₹${totalPending.toLocaleString('en-IN')}`} valueClass="text-red-600" />
            </div>

            {/* Defaulters */}
            {defaulters.length > 0 && (
              <div className="flex flex-col gap-2">
                <p className="text-sm font-semibold">Top Defaulters</p>
                <div className="rounded-md border border-border overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/50">
                      <tr>
                        <th className="text-left px-3 py-2 font-medium">Name</th>
                        <th className="text-left px-3 py-2 font-medium">Fee (₹)</th>
                        <th className="text-left px-3 py-2 font-medium">Days Overdue</th>
                      </tr>
                    </thead>
                    <tbody>
                      {defaulters.map((s) => {
                        const days = daysOverdue(month, s.due_day)
                        return (
                          <tr key={s.id} className="border-t border-border">
                            <td className="px-3 py-2">{s.name}</td>
                            <td className="px-3 py-2">₹{s.fee_amount.toLocaleString('en-IN')}</td>
                            <td className="px-3 py-2 text-red-600">
                              {days > 0 ? `${days} day${days > 1 ? 's' : ''}` : 'Due today'}
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            <Button size="sm" className="self-start" onClick={handleDownload}>
              Download Report
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

function StatCell({
  label,
  value,
  valueClass = '',
}: {
  label: string
  value: string
  valueClass?: string
}) {
  return (
    <div className="rounded-md border border-border px-3 py-2">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className={`text-lg font-bold mt-0.5 ${valueClass}`}>{value}</p>
    </div>
  )
}
